sample_app/config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #root "application#hello"
    #root :to => "static_pages#contact"
    root "microposts#index"
	get "static_pages/home"
	get "static_pages/help"
	get "static_pages/contact"
end

sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app/app/models/micropost.rb
class Micropost < ApplicationRecord
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

sample_app/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:user, :content)
    end
end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def help
	end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
	def full_title page_title = ""
		base_title = "Ruby on Rails Tutorial Sample App"
		page_title.empty? ? base_title : "#{page_title} | #{base_title}"
	end
end

sample_app/app/helpers/microposts_helper.rb
module MicropostsHelper
end

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  		<div class="container">
  			<%= link_to "sample_app", "#", id:"logo" %>
  			<nav>
  				<ul class="nav navbar-nav navbar-rigth">
  					<li><%= link_to "Home", "#" %></li>
  					<li><%= link_to "Help", "#" %></li>
  					<li><%= link_to "Login", "#" %></li>
  				</ul>
  			</nav>
  		</div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

sample_app/app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user, id: :micropost_user %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :micropost_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sample_app/app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

sample_app/app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.user %></td>
        <td><%= micropost.content %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

sample_app/app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

sample_app/app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @micropost.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

sample_app/app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>

<div class="center jumbotron">
	<h1>Contact</h1>
	<h1>Hello CongTT</h1>
	<h2>
		Mail me at 20140522@student.hust.edu.vn
	</h2>
</div>

sample_app/app/views/static_pages/help.html.erb
<% provide :title, "Help" %>

<h1>Help</h1>
<p>
	Get help on the Ruby on Rails tutorial at the 
	<a href="http://www.railstutorial.org/help">Rails Tutorial Help Page</a>
	To get help on this sample app, see the
	<a href="http://www.railstutorial.org/book"><em>Ruby on Rails tutorial book</em></a>
</p>

sample_app/app/views/static_pages/home.html.erb
<% provide :title, "Home" %>

<div class="center jumbotron">
	<h1>Sample App</h1>
	<h2>
		This is the homepage for 
		<a href="http://www.railstutorial.org">Ruby on Rails tutorial</a>
		sample application.
	</h2>

	<%= link_to "Sign up now!", "#", class: "btn btn-lg btn-primary" %>
</div>